### ISSUE TITLE
CI fails with MEM_OBJECT_ALLOCATION_FAILURE

### ISSUE THREAD

**Issue by majosm** [illinois-ceesd/mirgecom#109]
Test output:
```python
============================= test session starts ==============================
8
platform linux -- Python 3.8.5, pytest-6.1.0, py-1.9.0, pluggy-0.13.1
9
rootdir: /home/runner/work/mirgecom/mirgecom
10
collected 74 items
11

12
test_eos.py ..                                                           [  2%]
13
test_euler.py .............................................              [ 63%]
14
test_init.py ...                                                         [ 67%]
15
test_wave.py .......................F                                    [100%]
16

17
=================================== FAILURES ===================================
18
_ test_wave_stability[<array context factory for <pyopencl.Device 'pthread-Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz' on 'Portable Computing Language'>-4-problem3-0.025] _
19
Traceback (most recent call last):
20
  File "/home/runner/work/mirgecom/mirgecom/test/test_wave.py", line 234, in test_wave_stability
21
    fields = rk4_step(fields, t, dt, get_rhs)
22
  File "/home/runner/work/mirgecom/mirgecom/.miniforge3/envs/testing/lib/python3.8/site-packages/mirgecom-2020.1-py3.8.egg/mirgecom/integrators.py", line 41, in rk4_step
23
    k2 = rhs(t+dt/2, state + dt/2*k1)
24
  File "/home/runner/work/mirgecom/mirgecom/test/test_wave.py", line 221, in get_rhs
25
    result[0] += sym_eval(sym_f, t)
26
  File "/home/runner/work/mirgecom/mirgecom/test/test_wave.py", line 217, in sym_eval
27
    return sym.EvaluationMapper({"c": c, "x": nodes, "t": t})(expr)
28
  File "/home/runner/work/mirgecom/mirgecom/.miniforge3/envs/testing/lib/python3.8/site-packages/pymbolic/mapper/__init__.py", line 134, in __call__
29
    return method(expr, *args, **kwargs)
30
  File "/home/runner/work/mirgecom/mirgecom/.miniforge3/envs/testing/lib/python3.8/site-packages/pymbolic/mapper/evaluator.py", line 92, in map_sum
31
    return sum(self.rec(child) for child in expr.children)
32
  File "/home/runner/work/mirgecom/mirgecom/.miniforge3/envs/testing/lib/python3.8/site-packages/pymbolic/mapper/evaluator.py", line 92, in <genexpr>
33
    return sum(self.rec(child) for child in expr.children)
34
  File "/home/runner/work/mirgecom/mirgecom/.miniforge3/envs/testing/lib/python3.8/site-packages/pymbolic/mapper/__init__.py", line 134, in __call__
35
    return method(expr, *args, **kwargs)
36
  File "/home/runner/work/mirgecom/mirgecom/.miniforge3/envs/testing/lib/python3.8/site-packages/pymbolic/mapper/evaluator.py", line 96, in map_product
37
    return product(self.rec(child) for child in expr.children)
38
  File "/home/runner/work/mirgecom/mirgecom/.miniforge3/envs/testing/lib/python3.8/site-packages/pytools/__init__.py", line 978, in product
39
    return reduce(mul, iterable, 1)
40
  File "/home/runner/work/mirgecom/mirgecom/.miniforge3/envs/testing/lib/python3.8/site-packages/pymbolic/mapper/evaluator.py", line 96, in <genexpr>
41
    return product(self.rec(child) for child in expr.children)
42
  File "/home/runner/work/mirgecom/mirgecom/.miniforge3/envs/testing/lib/python3.8/site-packages/pymbolic/mapper/__init__.py", line 134, in __call__
43
    return method(expr, *args, **kwargs)
44
  File "/home/runner/work/mirgecom/mirgecom/.miniforge3/envs/testing/lib/python3.8/site-packages/pymbolic/mapper/evaluator.py", line 92, in map_sum
45
    return sum(self.rec(child) for child in expr.children)
46
  File "/home/runner/work/mirgecom/mirgecom/.miniforge3/envs/testing/lib/python3.8/site-packages/pymbolic/mapper/evaluator.py", line 92, in <genexpr>
47
    return sum(self.rec(child) for child in expr.children)
48
  File "/home/runner/work/mirgecom/mirgecom/.miniforge3/envs/testing/lib/python3.8/site-packages/pymbolic/mapper/__init__.py", line 134, in __call__
49
    return method(expr, *args, **kwargs)
50
  File "/home/runner/work/mirgecom/mirgecom/.miniforge3/envs/testing/lib/python3.8/site-packages/pymbolic/mapper/evaluator.py", line 96, in map_product
51
    return product(self.rec(child) for child in expr.children)
52
  File "/home/runner/work/mirgecom/mirgecom/.miniforge3/envs/testing/lib/python3.8/site-packages/pytools/__init__.py", line 978, in product
53
    return reduce(mul, iterable, 1)
54
  File "/home/runner/work/mirgecom/mirgecom/.miniforge3/envs/testing/lib/python3.8/site-packages/pymbolic/mapper/evaluator.py", line 96, in <genexpr>
55
    return product(self.rec(child) for child in expr.children)
56
  File "/home/runner/work/mirgecom/mirgecom/.miniforge3/envs/testing/lib/python3.8/site-packages/pymbolic/mapper/__init__.py", line 134, in __call__
57
    return method(expr, *args, **kwargs)
58
  File "/home/runner/work/mirgecom/mirgecom/.miniforge3/envs/testing/lib/python3.8/site-packages/pymbolic/mapper/evaluator.py", line 108, in map_power
59
    return self.rec(expr.base) ** self.rec(expr.exponent)
60
  File "/home/runner/work/mirgecom/mirgecom/.miniforge3/envs/testing/lib/python3.8/site-packages/pymbolic/mapper/__init__.py", line 134, in __call__
61
    return method(expr, *args, **kwargs)
62
  File "/home/runner/work/mirgecom/mirgecom/.miniforge3/envs/testing/lib/python3.8/site-packages/pymbolic/mapper/evaluator.py", line 92, in map_sum
63
    return sum(self.rec(child) for child in expr.children)
64
  File "/home/runner/work/mirgecom/mirgecom/.miniforge3/envs/testing/lib/python3.8/site-packages/pyopencl/array.py", line 1012, in __add__
65
    result = self._new_like_me(common_dtype)
66
  File "/home/runner/work/mirgecom/mirgecom/.miniforge3/envs/testing/lib/python3.8/site-packages/pyopencl/array.py", line 950, in _new_like_me
67
    return self.__class__(queue, self.shape, dtype,
68
  File "/home/runner/work/mirgecom/mirgecom/.miniforge3/envs/testing/lib/python3.8/site-packages/pyopencl/array.py", line 536, in __init__
69
    self.base_data = self.allocator(alloc_nbytes)
70
pyopencl._cl.MemoryError: create_buffer failed: MEM_OBJECT_ALLOCATION_FAILURE
```

**Comment by matthiasdiener** [comment]
This is not CI related. On my Mac Laptop (16 GB memory), running the tests with current grudge master essentially makes the whole system unusably slow. Running `git checkout 48e11e10626b01e001c2bfd245d4c74a996856d4` in grudge (ie, before https://github.com/inducer/grudge/pull/19) makes the tests run 10x faster and the system itself runs fine.

**Comment by inducer** [comment]
Reverting for now: https://github.com/inducer/grudge/pull/21

**Comment by inducer** [comment]
Reverted. Rerunning CI to verify.

**Comment by inducer** [comment]
https://github.com/illinois-ceesd/mirgecom/runs/1190090061

**Comment by matthiasdiener** [comment]
Seems to work:

https://github.com/illinois-ceesd/mirgecom/pull/108/checks?check_run_id=1190608747

**Comment by inducer** [comment]
Hmm, I guess we can close this then. I would still like to know why https://github.com/inducer/grudge/pull/19 caused problems, though.
