### ISSUE TITLE
Building docs fails due to failed SSL certificate validation

### ISSUE THREAD

**Issue by matthiasdiener** [illinois-ceesd/mirgecom#111]
On Lassen:

```bash
$ python
Python 3.8.5 | packaged by conda-forge | (default, Sep 24 2020, 16:13:24)
>>> import urllib3 #version 1.25.10
>>> http = urllib3.PoolManager()
>>> r = http.request('GET', 'https://documen.tician.de/pytools/objects.inv')
Traceback (most recent call last):
  File "/g/g91/diener3/Work/emirge.tmp/miniforge3/envs/dgfem/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/g/g91/diener3/Work/emirge.tmp/miniforge3/envs/dgfem/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/g/g91/diener3/Work/emirge.tmp/miniforge3/envs/dgfem/lib/python3.8/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/g/g91/diener3/Work/emirge.tmp/miniforge3/envs/dgfem/lib/python3.8/site-packages/urllib3/connection.py", line 362, in connect
    self.sock = ssl_wrap_socket(
  File "/g/g91/diener3/Work/emirge.tmp/miniforge3/envs/dgfem/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 384, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/g/g91/diener3/Work/emirge.tmp/miniforge3/envs/dgfem/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/g/g91/diener3/Work/emirge.tmp/miniforge3/envs/dgfem/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/g/g91/diener3/Work/emirge.tmp/miniforge3/envs/dgfem/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)
```

**Comment by inducer** [comment]
The certificate is fine according to [SSL Labs](https://www.ssllabs.com/ssltest/analyze.html?d=documen.tician.de&s=2a01%3a4f8%3a191%3a73ea%3a0%3a0%3a0%3a2&latest). Do you know which trust root conda is using?

**Comment by matthiasdiener** [comment]
This is what I get:

```bash
$ conda config --show
add_anaconda_token: True
add_pip_as_python_dependency: True
aggressive_update_packages:
  - ca-certificates
  - certifi
  - openssl
allow_conda_downgrades: False
allow_cycles: True
allow_non_channel_urls: False
allow_softlinks: False
always_copy: False
always_softlink: False
always_yes: None
anaconda_upload: None
auto_activate_base: True
auto_stack: 0
auto_update_conda: True
bld_path:
changeps1: True
channel_alias: https://conda.anaconda.org
channel_priority: flexible
channels:
  - conda-forge
client_ssl_cert: None
client_ssl_cert_key: None
clobber: False
conda_build: {}
create_default_packages: []
croot: /g/g91/diener3/Work/emirge.tmp/miniforge3/conda-bld
custom_channels:
  pkgs/main: https://repo.anaconda.com
  pkgs/r: https://repo.anaconda.com
  pkgs/pro: https://repo.anaconda.com
custom_multichannels:
  defaults:
    - https://repo.anaconda.com/pkgs/main
    - https://repo.anaconda.com/pkgs/r
  local:
debug: False
default_channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
default_python: 3.8
default_threads: None
deps_modifier: not_set
dev: False
disallowed_packages: []
download_only: False
dry_run: False
enable_private_envs: False
env_prompt: ({default_env})
envs_dirs:
  - /g/g91/diener3/Work/emirge.tmp/miniforge3/envs
  - /g/g91/diener3/.conda/envs
error_upload_url: https://conda.io/conda-post/unexpected-error
execute_threads: 1
extra_safety_checks: False
force: False
force_32bit: False
force_reinstall: False
force_remove: False
ignore_pinned: False
json: False
local_repodata_ttl: 1
migrated_channel_aliases: []
migrated_custom_channels: {}
non_admin_enabled: True
notify_outdated_conda: True
offline: False
override_channels_enabled: True
path_conflict: clobber
pinned_packages: []
pip_interop_enabled: False
pkgs_dirs:
  - /g/g91/diener3/Work/emirge.tmp/miniforge3/pkgs
  - /g/g91/diener3/.conda/pkgs
proxy_servers: {}
quiet: False
remote_backoff_factor: 1
remote_connect_timeout_secs: 9.15
remote_max_retries: 3
remote_read_timeout_secs: 60.0
repodata_fns:
  - current_repodata.json
  - repodata.json
repodata_threads: None
report_errors: None
restore_free_channel: False
rollback_enabled: True
root_prefix: /g/g91/diener3/Work/emirge.tmp/miniforge3
safety_checks: warn
sat_solver: pycosat
separate_format_cache: False
shortcuts: True
show_channel_urls: None
solver_ignore_timestamps: False
ssl_verify: True
subdir: linux-ppc64le
subdirs:
  - linux-ppc64le
  - noarch
target_prefix_override:
track_features: []
unsatisfiable_hints: True
unsatisfiable_hints_check_depth: 2
update_modifier: update_specs
use_index_cache: False
use_local: False
use_only_tar_bz2: False
verbosity: 0
verify_threads: 1
whitelist_channels: []

$ python -c "import ssl; print(ssl.get_default_verify_paths())"
DefaultVerifyPaths(cafile='/g/g91/diener3/Work/emirge.tmp/miniforge3/envs/dgfem/ssl/cert.pem', capath=None, openssl_cafile_env='SSL_CERT_FILE', openssl_cafile='/g/g91/diener3/Work/emirge.tmp/miniforge3/envs/dgfem/ssl/cert.pem', openssl_capath_env='SSL_CERT_DIR', openssl_capath='/g/g91/diener3/Work/emirge.tmp/miniforge3/envs/dgfem/ssl/certs')
```

**Comment by inducer** [comment]
Thanks for investigating the same things works just fine for me on my laptop (x86-64) with these packages:
<details>
<pre>
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
appdirs                   1.4.3                      py_1    conda-forge
attrs                     20.1.0             pyh9f0ad1d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
beautifulsoup4            4.9.1                      py_1    conda-forge
blinker                   1.4                        py_1    conda-forge
boolean.py                3.7                        py_0    conda-forge
brotlipy                  0.7.0           py38h1e0a361_1000    conda-forge
bzip2                     1.0.8                h516909a_3    conda-forge
c-ares                    1.16.1               h516909a_3    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py38h32f6830_0    conda-forge
cffi                      1.14.1           py38h5bae8af_0    conda-forge
chardet                   3.0.4           py38h32f6830_1006    conda-forge
conda                     4.8.5            py38h32f6830_0    conda-forge
conda-build               3.20.2           py38h32f6830_0    conda-forge
conda-forge-pinning       2020.09.14.18.14.00               0    conda-forge
conda-package-handling    1.7.0            py38h1e0a361_4    conda-forge
conda-smithy              3.7.10                     py_0    conda-forge
cryptography              3.1              py38h766eaa4_0    conda-forge
curl                      7.71.1               he644dc0_5    conda-forge
decorator                 4.4.2                      py_0    conda-forge
deprecated                1.2.10             pyh9f0ad1d_0    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
filelock                  3.0.12             pyh9f0ad1d_0    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
git                       2.28.0          pl526h5e3e691_1    conda-forge
gitdb                     4.0.5                      py_0    conda-forge
gitpython                 3.1.8                      py_0    conda-forge
glob2                     0.7                        py_0    conda-forge
icu                       67.1                 he1b5a44_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
iniconfig                 1.0.1              pyh9f0ad1d_0    conda-forge
ipykernel                 5.3.4            py38h23f93f0_0    conda-forge
ipyparallel               6.3.0            py38h32f6830_0    conda-forge
ipython                   7.18.1           py38h1cdfbd6_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
isodate                   0.6.0                      py_1    conda-forge
jedi                      0.15.2                   py38_0    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
jupyter_client            6.1.7                      py_0    conda-forge
jupyter_core              4.6.3            py38h32f6830_1    conda-forge
krb5                      1.17.1               hfafb76e_3    conda-forge
ld_impl_linux-64          2.34                 hc38a660_9    conda-forge
libarchive                3.3.3             h3a8160c_1008    conda-forge
libblas                   3.8.0               17_openblas    conda-forge
libcblas                  3.8.0               17_openblas    conda-forge
libclang-cpp10            10.0.1          default_hde54327_0    conda-forge
libcurl                   7.71.1               hcdd3856_5    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.3.0               h24d8f2e_14    conda-forge
libgfortran-ng            7.5.0               hdf63c60_14    conda-forge
libgomp                   9.3.0               h24d8f2e_14    conda-forge
libhwloc                  2.1.0                h3c4fd83_0    conda-forge
libiconv                  1.15              h516909a_1006    conda-forge
liblapack                 3.8.0               17_openblas    conda-forge
liblief                   0.10.1               he1b5a44_1    conda-forge
libllvm10                 10.0.1               he513fc3_1    conda-forge
libnghttp2                1.41.0               h8cfc5f6_2    conda-forge
libopenblas               0.3.10          pthreads_hb3c22a3_4    conda-forge
libsodium                 1.0.18               h516909a_1    conda-forge
libssh2                   1.9.0                hab1572f_5    conda-forge
libstdcxx-ng              9.3.0               hdf63c60_14    conda-forge
libxml2                   2.9.10               h72b56ed_2    conda-forge
license-expression        1.2                        py_0    conda-forge
lz4-c                     1.9.2                he1b5a44_3    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
mako                      1.1.3              pyh9f0ad1d_0    conda-forge
markupsafe                1.1.1            py38h1e0a361_1    conda-forge
metakernel                0.27.0             pyh9f0ad1d_0    conda-forge
metis                     5.1.0             he1b5a44_1005    conda-forge
more-itertools            8.4.0                      py_0    conda-forge
msrest                    0.6.19             pyh9f0ad1d_0    conda-forge
ncurses                   6.2                  he1b5a44_1    conda-forge
numpy                     1.19.1           py38h8854b6b_0    conda-forge
oauthlib                  3.0.1                      py_0    conda-forge
ocl-icd                   2.2.12            h516909a_1005    conda-forge
oct2py                    5.2.0              pyh9f0ad1d_0    conda-forge
octave_kernel             0.32.0             pyh9f0ad1d_0    conda-forge
openssl                   1.1.1h               h516909a_0    conda-forge
packaging                 20.4               pyh9f0ad1d_0    conda-forge
parso                     0.5.2                      py_0  
patchelf                  0.11                 he1b5a44_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
perl                      5.26.2            h516909a_1006    conda-forge
pexpect                   4.8.0            py38h32f6830_1    conda-forge
pickleshare               0.7.5           py38h32f6830_1001    conda-forge
pip                       20.2.1                     py_0    conda-forge
pkginfo                   1.5.0.1                    py_0    conda-forge
pluggy                    0.13.1           py38h32f6830_2    conda-forge
pocl                      1.5                  hb5afada_9    conda-forge
pocl-cuda                 1.5                  h926331d_9    conda-forge
portalocker               1.7.0            py38h32f6830_0    conda-forge
prompt-toolkit            3.0.7                      py_0    conda-forge
psutil                    5.7.2            py38h1e0a361_0    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
py                        1.9.0              pyh9f0ad1d_0    conda-forge
py-lief                   0.10.1           py38h950e882_1    conda-forge
pybind11                  2.5.0            py38hbf85e49_0    conda-forge
pycosat                   0.6.3           py38h1e0a361_1004    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pycrypto                  2.6.1           py38h1e0a361_1004    conda-forge
pygithub                  1.53                       py_0    conda-forge
pygments                  2.7.1                      py_0    conda-forge
pyjwt                     1.7.1                      py_0    conda-forge
pymetis                   2020.1                   pypi_0    pypi
pyopencl                  2020.2           py38hd103949_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pysocks                   1.7.1            py38h32f6830_1    conda-forge
pytest                    6.0.1            py38h32f6830_0    conda-forge
python                    3.8.5           h4d41432_2_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-libarchive-c       2.9                      py38_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytools                   2020.3.1           pyh9f0ad1d_0    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pyyaml                    5.3.1            py38h1e0a361_0    conda-forge
pyzmq                     19.0.2           py38ha71036d_0    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
requests                  2.24.0             pyh9f0ad1d_0    conda-forge
requests-oauthlib         1.3.0              pyh9f0ad1d_0    conda-forge
ripgrep                   12.1.1               h516909a_0    conda-forge
ruamel.yaml               0.16.12          py38h1e0a361_0    conda-forge
ruamel.yaml.clib          0.2.2            py38h1e0a361_0    conda-forge
ruamel_yaml               0.15.80         py38h1e0a361_1002    conda-forge
scipy                     1.5.2            py38h8c5af15_0    conda-forge
scrypt                    0.8.17           py38h766eaa4_0    conda-forge
setuptools                49.2.1           py38h32f6830_0    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
smmap                     3.0.4              pyh9f0ad1d_0    conda-forge
soupsieve                 2.0.1                      py_1    conda-forge
sqlite                    3.32.3               hcee41ef_1    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
toml                      0.10.1             pyh9f0ad1d_0    conda-forge
toolz                     0.10.0                     py_0    conda-forge
tornado                   6.0.4            py38h1e0a361_1    conda-forge
tqdm                      4.49.0             pyh9f0ad1d_0    conda-forge
traitlets                 5.0.4                      py_1    conda-forge
urllib3                   1.25.10                    py_0    conda-forge
vsts-python-api           0.1.22                     py_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
wheel                     0.34.2                     py_1    conda-forge
wrapt                     1.12.1           py38h1e0a361_1    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zeromq                    4.3.3                he1b5a44_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.5                h6597ccf_2    conda-forge
</pre>
</details>
I get this for the trust root:
```
DefaultVerifyPaths(cafile='/home/andreas/pack/miniforge3/envs/mytest/ssl/cert.pem', capath=None, openssl_cafile_env='SSL_CERT_FILE', openssl_cafile='/home/andreas/pack/miniforge3/envs/mytest/ssl/cert.pem', openssl_capath_env='SSL_CERT_DIR', openssl_capath='/home/andreas/pack/miniforge3/envs/mytest/ssl/certs')
```
So one easy question would be whether the files on lassen are the same as on x86-64. If not, then the next step would be to file a bug against the `ca-certificates` conda-forge package.
