### ISSUE TITLE
y0_euler driver compatibility

### ISSUE THREAD

**Issue by anderson2981** [illinois-ceesd/mirgecom#113]
The driver used to run the first Y0 simulation runs for the Kickoff meetings doesn't appear to work correctly. There are two possible locations to find this driver.  The y0euler branch in mirgecom and the experiments repository. Note there is no apparent link back to what version of mirgecom should be used with this driver in the experiments repo.

on Lassen:
y0_euler.py in the y0euler branch fails with the following error message

`Traceback (most recent call last):
  File "/usr/WS1/xpacc/Users/manders/software/Install/Lassen/Conda/envs/mirge.y0euler/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/WS1/xpacc/Users/manders/software/Install/Lassen/Conda/envs/mirge.y0euler/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/WS1/xpacc/Users/manders/software/Install/Lassen/Conda/envs/mirge.y0euler/lib/python3.8/site-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/usr/WS1/xpacc/Users/manders/software/Install/Lassen/Conda/envs/mirge.y0euler/lib/python3.8/site-packages/mpi4py/run.py", line 196, in main
    run_command_line(args)
  File "/usr/WS1/xpacc/Users/manders/software/Install/Lassen/Conda/envs/mirge.y0euler/lib/python3.8/site-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/usr/WS1/xpacc/Users/manders/software/Install/Lassen/Conda/envs/mirge.y0euler/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/WS1/xpacc/Users/manders/software/Install/Lassen/Conda/envs/mirge.y0euler/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/WS1/xpacc/Users/manders/software/Install/Lassen/Conda/envs/mirge.y0euler/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "y0_euler.py", line 305, in <module>
    main()
  File "y0_euler.py", line 288, in main
    advance_state(rhs=my_rhs, timestepper=timestepper, checkpoint=my_checkpoint,
  File "/usr/WS1/xpacc/Users/manders/software/Install/Lassen/MirgeCom/y0euler/mirgecom/mirgecom/steppers.py", line 60, in advance_state
    state = timestepper(state=state, t=t, dt=dt, rhs=rhs)
  File "/usr/WS1/xpacc/Users/manders/software/Install/Lassen/MirgeCom/y0euler/mirgecom/mirgecom/integrators.py", line 40, in rk4_step
    k1 = rhs(t, state)
  File "y0_euler.py", line 272, in my_rhs
    return inviscid_operator(discr, q=state, t=t,
  File "/usr/WS1/xpacc/Users/manders/software/Install/Lassen/MirgeCom/y0euler/mirgecom/mirgecom/euler.py", line 308, in inviscid_operator
    domain_boundary_flux = sum(
  File "/usr/WS1/xpacc/Users/manders/software/Install/Lassen/MirgeCom/y0euler/mirgecom/mirgecom/euler.py", line 311, in <genexpr>
    q_tpair=boundaries[btag].boundary_pair(discr, q, t=t,
  File "/usr/WS1/xpacc/Users/manders/software/Install/Lassen/MirgeCom/y0euler/mirgecom/mirgecom/boundary.py", line 48, in boundary_pair
    return TracePair(btag, int_soln, ext_soln)
TypeError: __init__() takes 2 positional arguments but 4 were given
Traceback (most recent call last):
  File "/usr/WS1/xpacc/Users/manders/software/Install/Lassen/Conda/envs/mirge.y0euler/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/WS1/xpacc/Users/manders/software/Install/Lassen/Conda/envs/mirge.y0euler/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/WS1/xpacc/Users/manders/software/Install/Lassen/Conda/envs/mirge.y0euler/lib/python3.8/site-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/usr/WS1/xpacc/Users/manders/software/Install/Lassen/Conda/envs/mirge.y0euler/lib/python3.8/site-packages/mpi4py/run.py", line 196, in main
    run_command_line(args)
  File "/usr/WS1/xpacc/Users/manders/software/Install/Lassen/Conda/envs/mirge.y0euler/lib/python3.8/site-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/usr/WS1/xpacc/Users/manders/software/Install/Lassen/Conda/envs/mirge.y0euler/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/WS1/xpacc/Users/manders/software/Install/Lassen/Conda/envs/mirge.y0euler/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/WS1/xpacc/Users/manders/software/Install/Lassen/Conda/envs/mirge.y0euler/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "y0_euler.py", line 305, in <module>
    main()
  File "y0_euler.py", line 288, in main
    advance_state(rhs=my_rhs, timestepper=timestepper, checkpoint=my_checkpoint,
  File "/usr/WS1/xpacc/Users/manders/software/Install/Lassen/MirgeCom/y0euler/mirgecom/mirgecom/steppers.py", line 60, in advance_state
    state = timestepper(state=state, t=t, dt=dt, rhs=rhs)
  File "/usr/WS1/xpacc/Users/manders/software/Install/Lassen/MirgeCom/y0euler/mirgecom/mirgecom/integrators.py", line 40, in rk4_step
    k1 = rhs(t, state)
  File "y0_euler.py", line 272, in my_rhs
    return inviscid_operator(discr, q=state, t=t,
  File "/usr/WS1/xpacc/Users/manders/software/Install/Lassen/MirgeCom/y0euler/mirgecom/mirgecom/euler.py", line 308, in inviscid_operator
    domain_boundary_flux = sum(
  File "/usr/WS1/xpacc/Users/manders/software/Install/Lassen/MirgeCom/y0euler/mirgecom/mirgecom/euler.py", line 311, in <genexpr>
    q_tpair=boundaries[btag].boundary_pair(discr, q, t=t,
  File "/usr/WS1/xpacc/Users/manders/software/Install/Lassen/MirgeCom/y0euler/mirgecom/mirgecom/boundary.py", line 48, in boundary_pair
    return TracePair(btag, int_soln, ext_soln)
TypeError: __init__() takes 2 positional arguments but 4 were given`

submit script:

`#! /bin/bash --login
#BSUB -nnodes 1
#BSUB -G uiuc
#BSUB -W 30
#BSUB -J mirge_Y0
#BSUB -q pdebug
#BSUB -o runOutput.%J
#BSUB -e runError.%J

module load gcc/8.3.1
echo "which conda"
echo `which conda`
conda activate mirge.y0euler
echo "conda state"
conda info
echo "which python"
echo `which python`

echo "#### take 2 ####"
source $CONDA_PATH/bin/activate mirge.y0euler
echo "which python"
echo `which python`

echo "PATH"
echo $PATH

nnodes=$(echo $LSB_MCPU_HOSTS | wc -w)
nnodes=$((nnodes/2-1))
nproc=$((4*nnodes)) # 4 ranks per node, 1 per GPU
export XDG_CACHE_HOME="/tmp/manders/xdg-scratch" # See above on why this is important

origin=$(pwd)
examples_dir=${1-$origin}
declare -i exitcode=0
echo "Running Y0 mirge ..."
echo "Running parallel mirge: $example"        
echo "lrun -g 1 -n $nproc python -m mpi4py y0_euler.py > euler.out"
lrun -g 1 -n $nproc python -m mpi4py y0_euler.py > euler.out
#lrun -g 1 -n $nproc python y0_euler.py > euler.out

echo "Done running Y0 mirge!"`

**Comment by majosm** [comment]
I think the experiments repo is still kind of a work in progress. See [issue](https://github.com/illinois-ceesd/experiments/issues/3).

The y0euler branch doesn't specify which versions of meshmode/grudge/etc. it was originally run with, so @MTCam will probably need to tell you that (if he still has an environment for it). Otherwise you could look at the dates when the branch was being worked on and try to find what versions of those packages were available at the time.

**Comment by MTCam** [comment]
> The driver used to run the first Y0 simulation runs for the Kickoff meetings doesn't appear to work correctly. There are two possible locations to find this driver. The y0euler branch in mirgecom and the experiments repository. Note there is no apparent link back to what version of mirgecom should be used with this driver in the experiments repo.

I mistakenly assumed that just checking out y0euler branch would continue tracking the correct versions of the substrate packages.  Matt's suggestions to pick up based on date makes sense.   I do still have an environment that runs this on Quartz - so we should be able to pick off the version numbers from that if needed.

> 
> on Lassen:
> y0_euler.py in the y0euler branch fails with the following error message
>
(.....) 
> line 308, in inviscid_operator domain_boundary_flux = sum( File 
"/usr/WS1/xpacc/Users/manders/software/Install/Lassen/MirgeCom/y0euler/mirgecom/mirgecom/euler.py", line 311, in <genexpr> q_tpair=boundaries[btag].boundary_pair(discr, q, t=t, File "/usr/WS1/xpacc/Users/manders/software/Install/Lassen/MirgeCom/y0euler/mirgecom/mirgecom/boundary.py", line 48, in boundary_pair return TracePair(btag, int_soln, ext_soln) TypeError: __init__() takes 2 positional arguments but 4 were given`
> 

This error is due to the BC/interface changing out from under y0euler branch.  I think the best path to resolving all of this is to get Euler BCs merged into master and use the `experiments` version of the driver.  

I think it is worth noting our difficulty in getting this going.  We almost always run simulations that depend on unmerged/development work-in-progress.  We need a way to make sure we can reproduce these runs and the code used to run them.   Currently, our strategy causes the driver code that actually gets checked in to diverge from that which was actually used.

**Comment by inducer** [comment]
> so @MTCam will probably need to tell you that

I propose that we update the `requirements.txt` on this branch with the appropriate versions. @matthiasdiener, maybe that's a function that we could get the versions script in emirge to do (spit out a pinned `requirements.txt`)?

**Comment by MTCam** [comment]
FYI, some time back this was resolved by porting y0euler to then-current master.   I propose we close this particular issue.

**Comment by anderson2981** [comment]
Solved going forward with current version tracking.
