### ISSUE TITLE
mesh generation fails on multiple nodes

### ISSUE THREAD

**Issue by anderson2981** [illinois-ceesd/mirgecom#132]
Mesh generation fails on Lassen with multiple nodes for pulse-mpi.py in branch y0euler. Similar behavior was observed in the y0_euler.py driver.

Error messages from a run with dim=3 on a 32^3 mesh. 2 nodes, 4 gpus per node. 8 ranks total. Single node execution (1 node, 4 gpus) proceeds normally.

```bash
rank 1: received local mesh (size = 3530491)
rank 2: received local mesh (size = 3530763)
rank 3: received local mesh (size = 3531460)
rank 4: received local mesh (size = 3532393)
building face restriction: start
building face restriction: start
building face restriction: start
rank 0: sent all mesh partitions
rank 7: received local mesh (size = 3531691)
building face restriction: start
building face restriction: start
building face restriction: done
bdry comm rank 2 send begin
building face restriction: done
bdry comm rank 3 send begin
building face restriction: start
building face restriction: start
building face restriction: done
bdry comm rank 1 send begin
Traceback (most recent call last):
  File "/usr/WS1/xpacc/Users/manders/software/Install/Lassen/Conda/envs/mirge.y0euler/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/WS1/xpacc/Users/manders/software/Install/Lassen/Conda/envs/mirge.y0euler/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/WS1/xpacc/Users/manders/software/Install/Lassen/Conda/envs/mirge.y0euler/lib/python3.8/site-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/usr/WS1/xpacc/Users/manders/software/Install/Lassen/Conda/envs/mirge.y0euler/lib/python3.8/site-packages/mpi4py/run.py", line 196, in main
    run_command_line(args)
  File "/usr/WS1/xpacc/Users/manders/software/Install/Lassen/Conda/envs/mirge.y0euler/lib/python3.8/site-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/usr/WS1/xpacc/Users/manders/software/Install/Lassen/Conda/envs/mirge.y0euler/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/WS1/xpacc/Users/manders/software/Install/Lassen/Conda/envs/mirge.y0euler/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/WS1/xpacc/Users/manders/software/Install/Lassen/Conda/envs/mirge.y0euler/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/p/gpfs1/manders/work/CEESD/mirgeY0/pulseExample/2nodes/pulse-mpi.py", line 179, in <module>
    main()
  File "/p/gpfs1/manders/work/CEESD/mirgeY0/pulseExample/2nodes/pulse-mpi.py", line 109, in main
    local_mesh, global_nelements = create_parallel_grid(comm, generate_grid)
  File "/usr/WS1/xpacc/Users/manders/software/Install/Lassen/MirgeCom/mirgecom/mirgecom/simutil.py", line 198, in create_parallel_grid
    local_mesh = mesh_dist.receive_mesh_part()
  File "/usr/WS1/xpacc/Users/manders/software/Install/Lassen/MirgeCom/meshmode/meshmode/distributed.py", line 115, in receive_mesh_part
    result = self.mpi_comm.recv(
  File "mpi4py/MPI/Comm.pyx", line 1173, in mpi4py.MPI.Comm.recv
  File "mpi4py/MPI/msgpickle.pxi", line 302, in mpi4py.MPI.PyMPI_recv
  File "mpi4py/MPI/msgpickle.pxi", line 268, in mpi4py.MPI.PyMPI_recv_match
  File "mpi4py/MPI/msgpickle.pxi", line 111, in mpi4py.MPI.Pickle.load
  File "mpi4py/MPI/msgpickle.pxi", line 101, in mpi4py.MPI.Pickle.cloads
_pickle.UnpicklingError: invalid load key, '\x19'.
Traceback (most recent call last):
  File "/usr/WS1/xpacc/Users/manders/software/Install/Lassen/Conda/envs/mirge.y0euler/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/WS1/xpacc/Users/manders/software/Install/Lassen/Conda/envs/mirge.y0euler/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/WS1/xpacc/Users/manders/software/Install/Lassen/Conda/envs/mirge.y0euler/lib/python3.8/site-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/usr/WS1/xpacc/Users/manders/software/Install/Lassen/Conda/envs/mirge.y0euler/lib/python3.8/site-packages/mpi4py/run.py", line 196, in main
    run_command_line(args)
  File "/usr/WS1/xpacc/Users/manders/software/Install/Lassen/Conda/envs/mirge.y0euler/lib/python3.8/site-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/usr/WS1/xpacc/Users/manders/software/Install/Lassen/Conda/envs/mirge.y0euler/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/WS1/xpacc/Users/manders/software/Install/Lassen/Conda/envs/mirge.y0euler/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/WS1/xpacc/Users/manders/software/Install/Lassen/Conda/envs/mirge.y0euler/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/p/gpfs1/manders/work/CEESD/mirgeY0/pulseExample/2nodes/pulse-mpi.py", line 179, in <module>
    main()
  File "/p/gpfs1/manders/work/CEESD/mirgeY0/pulseExample/2nodes/pulse-mpi.py", line 109, in main
    local_mesh, global_nelements = create_parallel_grid(comm, generate_grid)
  File "/usr/WS1/xpacc/Users/manders/software/Install/Lassen/MirgeCom/mirgecom/mirgecom/simutil.py", line 198, in create_parallel_grid
    local_mesh = mesh_dist.receive_mesh_part()
  File "/usr/WS1/xpacc/Users/manders/software/Install/Lassen/MirgeCom/meshmode/meshmode/distributed.py", line 115, in receive_mesh_part
    result = self.mpi_comm.recv(
  File "mpi4py/MPI/Comm.pyx", line 1173, in mpi4py.MPI.Comm.recv
  File "mpi4py/MPI/msgpickle.pxi", line 302, in mpi4py.MPI.PyMPI_recv
  File "mpi4py/MPI/msgpickle.pxi", line 268, in mpi4py.MPI.PyMPI_recv_match
  File "mpi4py/MPI/msgpickle.pxi", line 111, in mpi4py.MPI.Pickle.load
  File "mpi4py/MPI/msgpickle.pxi", line 101, in mpi4py.MPI.Pickle.cloads
_pickle.UnpicklingError: invalid load key, '\x19'.
building face restriction: start
building face restriction: done
bdry comm rank 7 send begin
building face restriction: start
building face restriction: done
bdry comm rank 4 send begin
building face restriction: start
building face restriction: done
bdry comm rank 2 send begin
building face restriction: start
building face restriction: done
bdry comm rank 3 send begin
building face restriction: done
bdry comm rank 1 send begin
building face restriction: start
building face restriction: start
building face restriction: done
bdry comm rank 7 send begin
building face restriction: start
building face restriction: done
bdry comm rank 4 send begin
building face restriction: start
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 5 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 6 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
```

**Comment by inducer** [comment]
@matthiasdiener This reminds me of the issue with pickle on Lassen that you encountered early on. Was there a resolution to that?

**Comment by matthiasdiener** [comment]
> @matthiasdiener This reminds me of the issue with pickle on Lassen that you encountered early on. Was there a resolution to that?

Yeah, that seems like the same issue, but there was no resolution as far as I remember. It only happens for some drivers (vortex-mpi.py seems to work fine). If I remember correctly, this only affected Lassen.

**Comment by inducer** [comment]
@anderson2981 Does this happen reproducibly?

@matthiasdiener If so, could you work with @anderson2981 to boil this down to a specific object that is being pickled, so that we can reproduce this without MPI involvement? Simply insert `pickle.loads(pickle.dumps(obj))` before the MPI send.

**Comment by MTCam** [comment]
The issue appears to be related to grid size, which helps explain why the smaller examples work fine.  I suggest filing an issue against meshmode instead.   I think this script should reproduce the issue.
```python
from mpi4py import MPI
from functools import partial


def create_parallel_grid(comm, generate_grid):
    from meshmode.distributed import (
        MPIMeshDistributor,
        get_partition_by_pymetis,
    )
    num_parts = comm.Get_size()
    mesh_dist = MPIMeshDistributor(comm)
    global_nelements = 0

    if mesh_dist.is_mananger_rank():

        mesh = generate_grid()

        global_nelements = mesh.nelements

        part_per_element = get_partition_by_pymetis(mesh, num_parts)
        local_mesh = mesh_dist.send_mesh_parts(mesh, part_per_element, num_parts)
        del mesh

    else:
        local_mesh = mesh_dist.receive_mesh_part()

    return local_mesh, global_nelements


def main():

    dim = 3
    rank = 0
    box_ll = -0.5
    box_ur = 0.5
    comm = MPI.COMM_WORLD
    nproc = comm.Get_size()
    rank = comm.Get_rank()
    num_parts = nproc

    for nel_1d in [2, 4, 8, 16, 32, 64]:
        comm.Barrier()
        if rank == 0:
            print(f"Partitioning grid {nel_1d}x{nel_1d}x{nel_1d}"
                  f"into {num_parts} partitions.", flush=True)
        comm.Barrier()
        from meshmode.mesh.generation import generate_regular_rect_mesh
        if num_parts > 1:
            generate_grid = partial(generate_regular_rect_mesh, a=(box_ll,) * dim,
                                    b=(box_ur,) * dim, n=(nel_1d,) * dim)
            local_mesh, global_nelements = create_parallel_grid(comm, generate_grid)
        else:
            local_mesh = generate_regular_rect_mesh(
                a=(box_ll,) * dim, b=(box_ur,) * dim, n=(nel_1d,) * dim
            )
            global_nelements = local_mesh.nelements
        local_nelements = local_mesh.nelements

        if rank == 0:
            print(f"Number of elements in grid: {global_nelements}", flush=True)
        for irank in range(num_parts):
            if irank == rank:
                print(f"Rank({rank}): Number of local elements = {local_nelements}",
                      flush=True)
            comm.Barrier()
        comm.Barrier()


if __name__ == "__main__":
    main()
```

**Comment by MTCam** [comment]
Using 1 MPI rank / Lassen node does not seem to reproduce the issue.  8 nodes worked fine with 1 MPI rank/node.

**Comment by matthiasdiener** [comment]
This has some workarounds that we might test: https://bitbucket.org/mpi4py/mpi4py/issues/102/unpicklingerror-on-commrecv-after-iprobe

**Comment by matthiasdiener** [comment]
> This has some workarounds that we might test: https://bitbucket.org/mpi4py/mpi4py/issues/102/unpicklingerror-on-commrecv-after-iprobe

Turns out this does fix the issue.
