### ISSUE TITLE
Memory-allocation related crash with profiling on GPU

### ISSUE THREAD

**Issue by matthiasdiener** [illinois-ceesd/mirgecom#177]
When running (e.g.) vortex-mpi with profiling enabled, and a somewhat larger input size (`nel_1d = 200`), mirgecom crashes with the following error: 

```
building face restriction: done
Traceback (most recent call last):
  File "/g/g91/diener3/Work/emirge/miniforge3/envs/dgfem/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/g/g91/diener3/Work/emirge/miniforge3/envs/dgfem/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/g/g91/diener3/Work/emirge/miniforge3/envs/dgfem/lib/python3.8/site-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/g/g91/diener3/Work/emirge/miniforge3/envs/dgfem/lib/python3.8/site-packages/mpi4py/run.py", line 196, in main
    run_command_line(args)
  File "/g/g91/diener3/Work/emirge/miniforge3/envs/dgfem/lib/python3.8/site-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/g/g91/diener3/Work/emirge/miniforge3/envs/dgfem/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/g/g91/diener3/Work/emirge/miniforge3/envs/dgfem/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/g/g91/diener3/Work/emirge/miniforge3/envs/dgfem/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "vortex-mpi.py", line 174, in <module>
    main()
  File "/usr/WS1/diener3/Work/emirge/mirgecom/mirgecom/mpi.py", line 81, in wrapped_func
    func(*args, **kwargs)
  File "vortex-mpi.py", line 147, in main
    advance_state(rhs=my_rhs, timestepper=timestepper,
  File "/usr/WS1/diener3/Work/emirge/mirgecom/mirgecom/steppers.py", line 79, in advance_state
    state = timestepper(state=state, t=t, dt=dt, rhs=rhs)
  File "/usr/WS1/diener3/Work/emirge/mirgecom/mirgecom/integrators.py", line 41, in rk4_step
    k2 = rhs(t+dt/2, state + dt/2*k1)
  File "vortex-mpi.py", line 133, in my_rhs
    return inviscid_operator(discr, q=state, t=t,
  File "/usr/WS1/diener3/Work/emirge/mirgecom/mirgecom/euler.py", line 264, in inviscid_operator
    vol_flux = inviscid_flux(discr, eos, q)
  File "/usr/WS1/diener3/Work/emirge/mirgecom/mirgecom/euler.py", line 181, in inviscid_flux
    momentum=np.outer(mom, mom)/cv.mass + np.eye(dim)*p)
  File "/usr/WS1/diener3/Work/emirge/meshmode/meshmode/dof_array.py", line 177, in __add__
    def __add__(self, arg): return self._bop(op.add, self, arg)  # noqa: E704
  File "/usr/WS1/diener3/Work/emirge/meshmode/meshmode/dof_array.py", line 167, in _bop
    return self._like_me([
  File "/usr/WS1/diener3/Work/emirge/meshmode/meshmode/dof_array.py", line 168, in <listcomp>
    f(op1_i, op2_i)
  File "/usr/WS1/diener3/Work/emirge/pyopencl/pyopencl/array.py", line 1013, in __add__
    result = self._new_like_me(
  File "/usr/WS1/diener3/Work/emirge/pyopencl/pyopencl/array.py", line 966, in _new_like_me
    return self.__class__(queue, self.shape, dtype,
  File "/usr/WS1/diener3/Work/emirge/pyopencl/pyopencl/array.py", line 536, in __init__
    self.base_data = self.allocator(alloc_nbytes)
pyopencl._cl.MemoryError: memory_pool::allocate failed: MEM_OBJECT_ALLOCATION_FAILURE - failed to free memory for allocation
```

This only happens when running on the GPU, not on CPU.

I've tracked this to the handling of the lists of ProfileEvents in mirgecom/profiling.py:

https://github.com/illinois-ceesd/mirgecom/blob/31467cc8cfc6f752392dad99d221a190ce65791f/mirgecom/profiling.py#L229

```python
@dataclass
class ProfileEvent:
    """Class to hold a profile event that has not been seen by the profiler yet."""

    cl_event: cl._cl.Event
    program: lp.kernel.LoopKernel
    kwargs: dict
```

At the time of the above crash, the list is relatively small (18 KByte memory). It seems that these ProfileEvents are somehow allocated on the device?
In the above code, replacing

```python
self.profile_events.append(ProfileEvent(evt, program, kwargs))
```

with 

```python
foo = ProfileResult(1,2,3,4)
self.profile_events.append(foo)
```

(ie, changing ProfileEvent to ProfileResult) seems to work fine.

**Comment by matthiasdiener** [comment]
Tracked this further down to the `kwargs` argument of ProfileEvent, which contains `cl.Array`s, likely the source of this issue. Fixing this will be complicated, since we need the kwargs later to determine flop counts etc.

**Comment by inducer** [comment]
I agree with your assessment. The `kwargs` will keep those arrays alive much longer than needed. I should have caught this during review.

> Fixing this will be complicated, since we need the kwargs later to determine flop counts etc.

Not really though, right? We don't need the arrays, just their metadata. (size, dtype and such)

**Comment by matthiasdiener** [comment]
> > Fixing this will be complicated, since we need the kwargs later to determine flop counts etc.
> 
> Not really though, right? We don't need the arrays (when gathering flop counts etc.), just their metadata. (size, dtype and such)

Right, but we need to generate this metadata on every kernel execution, as far as I can see.

**Comment by inducer** [comment]
Yes, that's true. Let's see if it's a bottleneck. If not, we could do it with generated code.
