### ISSUE TITLE
Performance degradation in isolator

### ISSUE THREAD

**Issue by MTCam** [illinois-ceesd/mirgecom#616]
The automated timings for the [production isolator case](https://github.com/illinois-ceesd/drivers_y2-isolator) have been showing some performance regression.   The following is a plot of the per-step timing for the automated isolator timing runs.

<img width="1108" alt="Screen Shot 2022-02-25 at 7 51 50 AM" src="https://user-images.githubusercontent.com/8116930/156175411-193a9fba-d583-458d-b6b6-42ed3f7d6b66.png">

The intent of this issue is to track/record/develop a strategy for discovering the cause of *MIRGE-Com* performance issues.

As suggested by @matthiasdiener , we added memory tracking to the isolator case (https://github.com/illinois-ceesd/timing/commit/de174051ae1b1cd300d54d3a02fb285c328fa126).

**Comment by MTCam** [comment]
Here's an error we are getting after adding memory tracking:
```
++ grep -v INFO
Traceback (most recent call last):
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/emirge/miniforge3/envs/isolator.lazy.timing.env/bin/runalyzer", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/emirge/logpyle/bin/runalyzer", line 36, in <module>
    main()
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/emirge/logpyle/bin/runalyzer", line 25, in main
    exec(compile(args.commands, "--commands", "exec"),
  File "--commands", line 1, in <module>
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/emirge/logpyle/logpyle/runalyzer.py", line 39, in q
    return self.db.execute(self.mangle_sql(qry), extra_args)
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/emirge/logpyle/logpyle/runalyzer.py", line 206, in mangle_sql
    self.get_rank_agg_table(tbl, rank_aggregator),
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/emirge/logpyle/logpyle/runalyzer.py", line 52, in get_rank_agg_table
    self.db.execute("create temporary table %s as "
sqlite3.OperationalError: no such table: memory_usage_gpu
+ MAX_GPU_MEM_USAGE=
```
