### ISSUE TITLE
All examples fail to run in lazy mode with the fusion array context

### ISSUE THREAD

**Issue by MTCam** [illinois-ceesd/mirgecom#650]
Upon fresh installs of `mirgecom@fusion_actx`, the following error occurs when attempting to run any *MIRGE-Com* case in lazy mode:

```
Traceback (most recent call last):
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/miniforge3/envs/tau.fusion2/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/miniforge3/envs/tau.fusion2/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/miniforge3/envs/tau.fusion2/lib/python3.9/site-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/miniforge3/envs/tau.fusion2/lib/python3.9/site-packages/mpi4py/run.py", line 198, in main
    run_command_line(args)
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/miniforge3/envs/tau.fusion2/lib/python3.9/site-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/miniforge3/envs/tau.fusion2/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/miniforge3/envs/tau.fusion2/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/miniforge3/envs/tau.fusion2/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "pulse-mpi.py", line 379, in <module>
    main(actx_class, use_logmgr=args.log, use_overintegration=args.overintegration,
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/mirgecom/mirgecom/mpi.py", line 157, in wrapped_func
    func(*args, **kwargs)
  File "pulse-mpi.py", line 324, in main
    advance_state(rhs=my_rhs, timestepper=timestepper,
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/mirgecom/mirgecom/steppers.py", line 330, in advance_state
    _advance_state_stepper_func(
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/mirgecom/mirgecom/steppers.py", line 129, in _advance_state_stepper_func
    state = timestepper(state=state, t=t, dt=dt, rhs=compiled_rhs)
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/mirgecom/mirgecom/integrators/explicit_rk.py", line 33, in rk4_step
    k1 = rhs(t, state)
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/arraycontext/arraycontext/impl/pytato/compile.py", line 340, in __call__
    compiled_func = self._dag_to_compiled_func(
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/grudge/grudge/array_context.py", line 187, in _dag_to_compiled_func
    dict_of_named_arrays = unify_discretization_entity_tags(
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/meshmode/meshmode/pytato_utils.py", line 489, in unify_discretization_entity_tags
    discr_unification_helper(expr)
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/pytato/pytato/transform.py", line 169, in __call__
    return self.rec(expr, *args, **kwargs)
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/meshmode/meshmode/pytato_utils.py", line 108, in rec
    super().rec(expr)  # type: ignore
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/pytato/pytato/transform.py", line 165, in rec
    return method(expr, *args, **kwargs)
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/meshmode/meshmode/pytato_utils.py", line 444, in map_dict_of_named_arrays
    self.rec(subexpr)
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/meshmode/meshmode/pytato_utils.py", line 108, in rec
    super().rec(expr)  # type: ignore
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/pytato/pytato/transform.py", line 165, in rec
    return method(expr, *args, **kwargs)
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/meshmode/meshmode/pytato_utils.py", line 172, in map_index_lambda
    self.rec(bnd)
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/meshmode/meshmode/pytato_utils.py", line 108, in rec
    super().rec(expr)  # type: ignore
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/pytato/pytato/transform.py", line 165, in rec
    return method(expr, *args, **kwargs)
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/meshmode/meshmode/pytato_utils.py", line 172, in map_index_lambda
    self.rec(bnd)
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/meshmode/meshmode/pytato_utils.py", line 108, in rec
    super().rec(expr)  # type: ignore
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/pytato/pytato/transform.py", line 165, in rec
    return method(expr, *args, **kwargs)
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/meshmode/meshmode/pytato_utils.py", line 418, in map_einsum
    self.rec(arg)
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/meshmode/meshmode/pytato_utils.py", line 108, in rec
    super().rec(expr)  # type: ignore
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/pytato/pytato/transform.py", line 165, in rec
    return method(expr, *args, **kwargs)
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/meshmode/meshmode/pytato_utils.py", line 172, in map_index_lambda
    self.rec(bnd)
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/meshmode/meshmode/pytato_utils.py", line 108, in rec
    super().rec(expr)  # type: ignore
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/pytato/pytato/transform.py", line 165, in rec
    return method(expr, *args, **kwargs)
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/meshmode/meshmode/pytato_utils.py", line 418, in map_einsum
    self.rec(arg)
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/meshmode/meshmode/pytato_utils.py", line 108, in rec
    super().rec(expr)  # type: ignore
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/pytato/pytato/transform.py", line 165, in rec
    return method(expr, *args, **kwargs)
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/meshmode/meshmode/pytato_utils.py", line 386, in map_reshape
    self.rec(expr.array)
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/meshmode/meshmode/pytato_utils.py", line 108, in rec
    super().rec(expr)  # type: ignore
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/pytato/pytato/transform.py", line 165, in rec
    return method(expr, *args, **kwargs)
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/meshmode/meshmode/pytato_utils.py", line 172, in map_index_lambda
    self.rec(bnd)
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/meshmode/meshmode/pytato_utils.py", line 108, in rec
    super().rec(expr)  # type: ignore
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/pytato/pytato/transform.py", line 165, in rec
    return method(expr, *args, **kwargs)
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/meshmode/meshmode/pytato_utils.py", line 172, in map_index_lambda
    self.rec(bnd)
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/meshmode/meshmode/pytato_utils.py", line 108, in rec
    super().rec(expr)  # type: ignore
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/pytato/pytato/transform.py", line 165, in rec
    return method(expr, *args, **kwargs)
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/meshmode/meshmode/pytato_utils.py", line 172, in map_index_lambda
    self.rec(bnd)
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/meshmode/meshmode/pytato_utils.py", line 108, in rec
    super().rec(expr)  # type: ignore
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/pytato/pytato/transform.py", line 165, in rec
    return method(expr, *args, **kwargs)
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/meshmode/meshmode/pytato_utils.py", line 172, in map_index_lambda
    self.rec(bnd)
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/meshmode/meshmode/pytato_utils.py", line 108, in rec
    super().rec(expr)  # type: ignore
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/pytato/pytato/transform.py", line 165, in rec
    return method(expr, *args, **kwargs)
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/meshmode/meshmode/pytato_utils.py", line 332, in map_contiguous_advanced_index
    self.rec(expr.array)
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/meshmode/meshmode/pytato_utils.py", line 108, in rec
    super().rec(expr)  # type: ignore
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/pytato/pytato/transform.py", line 165, in rec
    return method(expr, *args, **kwargs)
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/meshmode/meshmode/pytato_utils.py", line 172, in map_index_lambda
    self.rec(bnd)
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/meshmode/meshmode/pytato_utils.py", line 108, in rec
    super().rec(expr)  # type: ignore
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/pytato/pytato/transform.py", line 165, in rec
    return method(expr, *args, **kwargs)
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/meshmode/meshmode/pytato_utils.py", line 172, in map_index_lambda
    self.rec(bnd)
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/meshmode/meshmode/pytato_utils.py", line 108, in rec
    super().rec(expr)  # type: ignore
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/pytato/pytato/transform.py", line 165, in rec
    return method(expr, *args, **kwargs)
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/meshmode/meshmode/pytato_utils.py", line 172, in map_index_lambda
    self.rec(bnd)
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/meshmode/meshmode/pytato_utils.py", line 108, in rec
    super().rec(expr)  # type: ignore
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/pytato/pytato/transform.py", line 165, in rec
    return method(expr, *args, **kwargs)
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/meshmode/meshmode/pytato_utils.py", line 176, in map_index_lambda
    hlo = index_lambda_to_high_level_op(expr)
  File "/Users/mtcampbe/CEESD/devel/tau/fusion2/emirge/pytato/pytato/raising.py", line 330, in index_lambda_to_high_level_op
    raise UnknownIndexLambdaExpr(expr.expr)
pytato.diagnostic.UnknownIndexLambdaExpr: NaN if _in0[_0, _1] else _in2[_0, _1]
Abort(1) on node 0 (rank 0 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
```

**Comment by anderson2981** [comment]
I see this same error in my production CI for isolator.

**Comment by matthiasdiener** [comment]
I think https://github.com/inducer/pytato/pull/312 will fix this

**Comment by inducer** [comment]
Now merged, but it's not yet in @kaushikcfd's branch: https://github.com/inducer/pytato/compare/main...kaushikcfd:main

**Comment by kaushikcfd** [comment]
Pulled in my my branch as well.

**Comment by MTCam** [comment]
Nice. Thanks!
