### ISSUE TITLE
New failure using limiter functions

### ISSUE THREAD

**Issue by MTCam** [illinois-ceesd/mirgecom#747]
Looks like some change in upstream packages are causing a new issue with the bound_preserving_limiter function.   
@matthiasdiener pushed a PR to fix this.
Fixed by inducer/pyopencl#604

Here's a representative error message produced from `pytest -x test_limiter.py`:

```
        # apply positivity-preserving limiter
>       limited_field = bound_preserving_limiter(dcoll, field, mmin=0.0)

test_limiter.py:56: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../mirgecom/limiter.py:104: in bound_preserving_limiter
    _theta = actx.np.minimum(
../../arraycontext/arraycontext/impl/pyopencl/fake_numpy.py:289: in minimum
    return rec_multimap_array_container(
../../arraycontext/arraycontext/container/traversal.py:312: in rec_multimap_array_container
    return _multimap_array_container_impl(
../../arraycontext/arraycontext/container/traversal.py:210: in _multimap_array_container_impl
    return _map_array_container_impl(
../../arraycontext/arraycontext/container/traversal.py:114: in _map_array_container_impl
    return rec(ary)
../../arraycontext/arraycontext/container/traversal.py:109: in rec
    return deserialize_container(_ary, [
../../arraycontext/arraycontext/container/traversal.py:110: in <listcomp>
    (key, frec(subary)) for key, subary in iterable
../../arraycontext/arraycontext/container/traversal.py:107: in rec
    return f(_ary)
../../arraycontext/arraycontext/container/traversal.py:206: in wrapper
    return f(*new_args)
../../miniforge3/envs/tau.svm.test/lib/python3.9/site-packages/pyopencl/array.py:3003: in minimum
    out_dtype = _get_common_dtype(a, b, queue)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

obj1 = 1.0
obj2 = cl.TaggableCLArray([[0.988, 0.988, 0.988],
       [0.994, 0.994, 0.994],
       [0.988, 0.988, 0.988],
       [0.994, ...      [1.   , 1.   , 1.   ],
       [1.   , 1.   , 1.   ],
       [1.   , 1.   , 1.   ],
       [1.   , 1.   , 1.   ]])
queue = <pyopencl._cl.CommandQueue object at 0x159c2a7c0>

    def _get_common_dtype(obj1, obj2, queue):
        if queue is None:
            raise ValueError("PyOpenCL array has no queue; call .with_queue() to "
                    "add one in order to be able to perform operations")
    
        dsupport = has_double_support(queue.device)
        cache_key = None
>       o1_dtype = obj1.dtype
E       AttributeError: 'float' object has no attribute 'dtype'

../../miniforge3/envs/tau.svm.test/lib/python3.9/site-packages/pyopencl/array.py:69: AttributeError

```

At driver runtime the problem, (produced by `python -m mpi4py autoignition-mpi.py`), looks like this:

```
Traceback (most recent call last):
  File "/Users/mtcampbe/CEESD/devel/tau/svm-test/svmfuse/arraycontext/arraycontext/container/traversal.py", line 105, in rec
    iterable = serialize_container(_ary)
  File "/Users/mtcampbe/CEESD/devel/tau/svm-test/svmfuse/miniforge3/envs/tau.svm.test/lib/python3.9/functools.py", line 888, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/Users/mtcampbe/CEESD/devel/tau/svm-test/svmfuse/arraycontext/arraycontext/container/__init__.py", line 166, in serialize_container
    raise NotAnArrayContainerError(
arraycontext.container.NotAnArrayContainerError: 'TaggableCLArray' cannot be serialized as a container

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mtcampbe/CEESD/devel/tau/svm-test/svmfuse/miniforge3/envs/tau.svm.test/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/mtcampbe/CEESD/devel/tau/svm-test/svmfuse/miniforge3/envs/tau.svm.test/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/mtcampbe/CEESD/devel/tau/svm-test/svmfuse/miniforge3/envs/tau.svm.test/lib/python3.9/site-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/Users/mtcampbe/CEESD/devel/tau/svm-test/svmfuse/miniforge3/envs/tau.svm.test/lib/python3.9/site-packages/mpi4py/run.py", line 198, in main
    run_command_line(args)
  File "/Users/mtcampbe/CEESD/devel/tau/svm-test/svmfuse/miniforge3/envs/tau.svm.test/lib/python3.9/site-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/Users/mtcampbe/CEESD/devel/tau/svm-test/svmfuse/miniforge3/envs/tau.svm.test/lib/python3.9/runpy.py", line 288, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/mtcampbe/CEESD/devel/tau/svm-test/svmfuse/miniforge3/envs/tau.svm.test/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/mtcampbe/CEESD/devel/tau/svm-test/svmfuse/miniforge3/envs/tau.svm.test/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "autoignition-mpi.py", line 680, in <module>
    main(actx_class, use_logmgr=args.log, use_leap=args.leap,
  File "/Users/mtcampbe/CEESD/devel/tau/svm-test/svmfuse/mirgecom/mirgecom/mpi.py", line 157, in wrapped_func
    func(*args, **kwargs)
  File "autoignition-mpi.py", line 611, in main
    advance_state(rhs=my_rhs, timestepper=timestepper,
  File "/Users/mtcampbe/CEESD/devel/tau/svm-test/svmfuse/mirgecom/mirgecom/steppers.py", line 425, in advance_state
    _advance_state_stepper_func(
  File "/Users/mtcampbe/CEESD/devel/tau/svm-test/svmfuse/mirgecom/mirgecom/steppers.py", line 154, in _advance_state_stepper_func
    state, dt = pre_step_callback(state=state, step=istep, t=t, dt=dt)
  File "autoignition-mpi.py", line 522, in my_pre_step
    fluid_state = construct_fluid_state(limiter(cv, temp=tseed), tseed)
  File "autoignition-mpi.py", line 505, in limiter
    spec_lim = make_obj_array([
  File "autoignition-mpi.py", line 506, in <listcomp>
    bound_preserving_limiter(dcoll, cv.species_mass_fractions[i], mmax=1.0)
  File "/Users/mtcampbe/CEESD/devel/tau/svm-test/svmfuse/mirgecom/mirgecom/limiter.py", line 104, in bound_preserving_limiter
    _theta = actx.np.minimum(
  File "/Users/mtcampbe/CEESD/devel/tau/svm-test/svmfuse/arraycontext/arraycontext/impl/pyopencl/fake_numpy.py", line 289, in minimum
    return rec_multimap_array_container(
  File "/Users/mtcampbe/CEESD/devel/tau/svm-test/svmfuse/arraycontext/arraycontext/container/traversal.py", line 312, in rec_multimap_array_container
    return _multimap_array_container_impl(
  File "/Users/mtcampbe/CEESD/devel/tau/svm-test/svmfuse/arraycontext/arraycontext/container/traversal.py", line 210, in _multimap_array_container_impl
    return _map_array_container_impl(
  File "/Users/mtcampbe/CEESD/devel/tau/svm-test/svmfuse/arraycontext/arraycontext/container/traversal.py", line 114, in _map_array_container_impl
    return rec(ary)
  File "/Users/mtcampbe/CEESD/devel/tau/svm-test/svmfuse/arraycontext/arraycontext/container/traversal.py", line 109, in rec
    return deserialize_container(_ary, [
  File "/Users/mtcampbe/CEESD/devel/tau/svm-test/svmfuse/arraycontext/arraycontext/container/traversal.py", line 110, in <listcomp>
    (key, frec(subary)) for key, subary in iterable
  File "/Users/mtcampbe/CEESD/devel/tau/svm-test/svmfuse/arraycontext/arraycontext/container/traversal.py", line 107, in rec
    return f(_ary)
  File "/Users/mtcampbe/CEESD/devel/tau/svm-test/svmfuse/arraycontext/arraycontext/container/traversal.py", line 206, in wrapper
    return f(*new_args)
  File "/Users/mtcampbe/CEESD/devel/tau/svm-test/svmfuse/miniforge3/envs/tau.svm.test/lib/python3.9/site-packages/pyopencl/array.py", line 3003, in minimum
    out_dtype = _get_common_dtype(a, b, queue)
  File "/Users/mtcampbe/CEESD/devel/tau/svm-test/svmfuse/miniforge3/envs/tau.svm.test/lib/python3.9/site-packages/pyopencl/array.py", line 69, in _get_common_dtype
    o1_dtype = obj1.dtype
AttributeError: 'float' object has no attribute 'dtype'
```

**Comment by inducer** [comment]
https://pypi.org/project/pyopencl/2022.2.2/ should take care of this. It's on the package index now, and hopefully on conda-forge soon.
