### ISSUE TITLE
Errors with isolator when running > 4 lassen GPUs

### ISSUE THREAD

**Issue by MTCam** [illinois-ceesd/mirgecom#748]
This error is produced by running the following commands on Lassen:

Use this driver@branch:
`drivers_y2-isolator@new_art_visc`

Running this test:
`smoke_test_injection_3d`

Change `order=1` --> `order=3` in run_params_multi.yaml
(YAML config file shared below)

Init phase (succeeds ok):
`jsrun -a 1 -g 1 -n 8 ./isolator_injection_init.py -i run_params_multi.yaml --lazy`

Run phase (where the error happens):
`jsrun -a 1 -g 1 -n 8 ./isolator_injection_run.py -i run_params_multi.yaml -r restart_data/isolator_init_000000 --lazy`

The error is really long and challenging to post.  Here's part of it: 

```
 12022-09-12 14:38:37,670 - INFO - meshmode.array_context - Transforming kernel with 55 statements.                                                                         
 22022-09-12 14:38:37,710 - INFO - meshmode.array_context - Array Contraction: Contracting 7 temps                                                                          
 3Traceback (most recent call last):                                                                                                                                        
 4  File "/p/gpfs1/mtcampbe/CEESD/Experimental/svm/svmfuse/arraycontext/arraycontext/impl/pytato/__init__.py", line 390, in freeze                                          
 5    pt_prg = self._freeze_prg_cache[normalized_expr]                                                                                                                      
 6KeyErrorTraceback (most recent call last):                                                                                                                                
 7  File "/p/gpfs1/mtcampbe/CEESD/Experimental/svm/svmfuse/arraycontext/arraycontext/impl/pytato/__init__.py", line 390, in freeze                                          
 8    pt_prg = self._freeze_prg_cache[normalized_expr]                                                                                                                      
 9KeyError: DictOfNamedArrays({'_arycv_mass_0': IndexLambda(expr=Sum((0, Subscript(Variable('_in1'), (Variable('_0'), Variable('_1'))))), shape=(0, 10), dtype='float64', b\
  indings={'_in1': AdvancedIndexInContiguousAxes(axes=(Axis(tags=frozenset({DiscretizationElementAxisTag()})), Axis(tags=frozenset({DiscretizationDOFAxisTag()}))), array=P\
  laceholder(axes=(Axis(tags=frozenset({DiscretizationElementAxisTag()})), Axis(tags=frozenset({DiscretizationDOFAxisTag()}))), tags={FEMEinsumTag(indices=((FreeEinsumInde\
  x(discr_entity=DiscretizationElementAxisTag(), length=11712), FreeEinsumIndex(discr_entity=DiscretizationDOFAxisTag(), length=20)), (FreeEinsumIndex(discr_entity=Discret\
  izationElementAxisTag(), length=11712), FreeEinsumIndex(discr_entity=DiscretizationDOFAxisTag(), length=20)))), PrefixNamed(prefix='cse')}, shape=(11712, 20), dtype='flo\
  at64', name='_actx_dw'), indices=(Reshape(tags={PrefixNamed(prefix='from_el_indices')}, array=Placeholder(tags={PrefixNamed(prefix='from_el_indices')}, shape=(0), dtype=\
  'int32', name='_actx_dw_0'), newshape=(0, 1), order='C'), AdvancedIndexInContiguousAxes(array=Placeholder(tags={PrefixNamed(prefix='dof_pick_lists')}, shape=(4, 10), dty\
  pe='int32', name='_actx_dw_1'), indices=(Placeholder(tags={PrefixNamed(prefix='dof_pick_list_indices')}, shape=(0), dtype='int8', name='_actx_dw_2'), NormalizedSlice(sta\
  rt=0, stop=10, step=1)))))}), '_arycv_energy_0': IndexLambda(expr=Sum((0, Subscript(Variable('_in1'), (Variable('_0'), Variable('_1'))))), shape=(0, 10), dtype='float64'\
  , bindings={'_in1': AdvancedIndexInContiguousAxes(axes=(Axis(tags=frozenset({DiscretizationElementAxisTag()})), Axis(tags=frozenset({DiscretizationDOFAxisTag()}))), arra\
  y=Placeholder(axes=(Axis(tags=frozenset({DiscretizationElementAxisTag()})), Axis(tags=frozenset({DiscretizationDOFAxisTag()}))), tags={FEMEinsumTag(indices=((FreeEinsumI\
  ndex(discr_entity=DiscretizationElementAxisTag(), length=11712), FreeEinsumIndex(discr_entity=DiscretizationDOFAxisTag(), length=20)), (FreeEinsumIndex(discr_entity=Disc\
  retizationElementAxisTag(), length=11712), FreeEinsumIndex(discr_entity=DiscretizationDOFAxisTag(), length=20))))}, shape=(11712, 20), dtype='float64', name='_actx_dw_3'\
  ), indices=(Reshape(tags={PrefixNamed(prefix='from_el_indices')}, array=Placeholder(tags={PrefixNamed(prefix='from_el_indices')}, shape=(0), dtype='int32', name='_actx_d\
  w_4'), newshape=(0, 1), order='C'), AdvancedIndexInContiguousAxes(array=Placeholder(tags={PrefixNamed(prefix='dof_pick_lists')}, shape=(4, 10), dtype='int32', name='_act\
  x_dw_5'), indices=(Placeholder(tags={PrefixNamed(prefix='dof_pick_list_indices')}, shape=(0), dtype='int8', name='_actx_dw_6'), NormalizedSlice(start=0, stop=10, step=1)\
  ))))}), '_arycv_momentum_0_0': IndexLambda(expr=Sum((0, Subscript(Variable('_in1'), (Variable('_0'), Variable('_1'))))), shape=(0, 10), dtype='float64', bindings={'_in1'\
  : AdvancedIndexInContiguousAxes(axes=(Axis(tags=frozenset({DiscretizationElementAxisTag()})), Axis(tags=frozenset({DiscretizationDOFAxisTag()}))), array=Placeholder(axes\
  =(Axis(tags=frozenset({DiscretizationElementAxisTag()})), Axis(tags=frozenset({DiscretizationDOFAxisTag()}))), tags={FEMEinsumTag(indices=((FreeEinsumIndex(discr_entity=\
  DiscretizationElementAxisTag(), length=11712), FreeEinsumIndex(discr_entity=DiscretizationDOFAxisTag(), length=20)), (FreeEinsumIndex(discr_entity=DiscretizationElementA\
  xisTag(), length=11712), FreeEinsumIndex(discr_entity=DiscretizationDOFAxisTag(), length=20)))), PrefixNamed(prefix='cse')}, shape=(11712, 20), dtype='float64', name='_a\
  ctx_dw_7'), indices=(Reshape(tags={PrefixNamed(prefix='from_el_indices')}, array=Placeholder(tags={PrefixNamed(prefix='from_el_indices')}, shape=(0), dtype='int32', name\
  ='_actx_dw_8'), newshape=(0, 1), order='C'), AdvancedIndexInContiguousAxes(array=Placeholder(tags={PrefixNamed(prefix='dof_pick_lists')}, shape=(4, 10), dtype='int32', n\
  ame='_actx_dw_9'), indices=(Placeholder(tags={PrefixNamed(prefix='dof_pick_list_indices')}, shape=(0), dtype='int8', name='_actx_dw_10'), NormalizedSlice(start=0, stop=1\
  0, step=1)))))}), '_arycv_momentum_1_0': IndexLambda(expr=Sum((0, Subscript(Variable('_in1'), (Variable('_0'), Variable('_1'))))), shape=(0, 10), dtype='float64', bindin\
  gs={'_in1': AdvancedIndexInContiguousAxes(axes=(Axis(tags=frozenset({DiscretizationElementAxisTag()})), Axis(tags=frozenset({DiscretizationDOFAxisTag()}))), array=Placeh\

(.....)
10                                                                                                                 
11During handling of the above exception, another exception occurred:                                              
12                                                                                                                 
13Traceback (most recent call last):                                                                               
14  File "/p/gpfs1/mtcampbe/CEESD/Experimental/svm/svmfuse/miniforge3/envs/x.svmfuse/lib/python3.9/runpy.py", line\
   197, in _run_module_as_main                                                                                     
15    return _run_code(code, main_globals, None,                                                                   
16  File "/p/gpfs1/mtcampbe/CEESD/Experimental/svm/svmfuse/miniforge3/envs/x.svmfuse/lib/python3.9/runpy.py", line\
   87, in _run_code                                                                                                
17    exec(code, run_globals)                                                                                      
18  File "/p/gpfs1/mtcampbe/CEESD/Experimental/svm/svmfuse/miniforge3/envs/x.svmfuse/lib/python3.9/site-packages/m\
  pi4py/__main__.py", line 7, in <module>                                                                          
19    main()                                                                                                       
20  File "/p/gpfs1/mtcampbe/CEESD/Experimental/svm/svmfuse/miniforge3/envs/x.svmfuse/lib/python3.9/site-packages/m\
  pi4py/run.py", line 198, in main                                                                                 
21    run_command_line(args)                                                                                       
22  File "/p/gpfs1/mtcampbe/CEESD/Experimental/svm/svmfuse/miniforge3/envs/x.svmfuse/lib/python3.9/site-packages/m\
  pi4py/run.py", line 47, in run_command_line                                                                      
23    run_path(sys.argv[0], run_name='__main__')                                                                   
24  File "/p/gpfs1/mtcampbe/CEESD/Experimental/svm/svmfuse/miniforge3/envs/x.svmfuse/lib/python3.9/runpy.py", line\
   288, in run_path                                                                                                
25    return _run_module_code(code, init_globals, run_name,                                                        
26  File "/p/gpfs1/mtcampbe/CEESD/Experimental/svm/svmfuse/miniforge3/envs/x.svmfuse/lib/python3.9/runpy.py", line\      
27    _run_code(code, mod_globals, init_globals,                                                                                                  
28  File "/p/gpfs1/mtcampbe/CEESD/Experimental/svm/svmfuse/miniforge3/envs/x.svmfuse/lib/python3.9/runpy.py", line 87, in _run_code               
29    exec(code, run_globals)                                                                                                                     
30  File "isolator_injection_run.py", line 1750, in <module>                                                                                      
31: DictOfNamedArrays({'_arycv_mass_0': IndexLambda(expr=Sum((0, Subscript(Variable('_in1'), (Variable('_0'), Variable('_1'))))), shape=(0, 10), \
  dtype='float64', bindings={'_in1': AdvancedIndexInContiguousAxes(axes=(Axis(tags=frozenset({DiscretizationElementAxisTag()})), Axis(tags=frozen\
  set({DiscretizationDOFAxisTag()}))), array=Placeholder(axes=(Axis(tags=frozenset({DiscretizationElementAxisTag()})), Axis(tags=frozenset({Discr\
  etizationDOFAxisTag()}))), tags={FEMEinsumTag(indices=((FreeEinsumIndex(discr_entity=DiscretizationElementAxisTag(), length=11712), FreeEinsumI\
  ndex(discr_entity=DiscretizationDOFAxisTag(), length=20)), (FreeEinsumIndex(discr_entity=DiscretizationElementAxisTag(), length=11712), FreeEin\
  sumIndex(discr_entity=DiscretizationDOFAxisTag(), length=20)))), PrefixNamed(prefix='cse')}, shape=(11712, 20), dtype='float64', name='_actx_dw\
(....)
38  File "/p/gpfs1/mtcampbe/CEESD/Experimental/svm/svmfuse/arraycontext/arraycontext/impl/pytato/__init__.py", line 419, in freeze                
39ambda(expr=Product((0, Subscript(Variable('_in1'), (Variable('_0'), Variable('_1'))))), shape=(0, 10), dtype='float64', bindings={'_in1': Index\
  Lambda(expr=Sum((0, Subscript(Variable('_in1'), (Variable('_0'), Variable('_1'))))), shape=(0, 10), dtype='float64', bindings={'_in1': (...)})}\
  )})})})                                                                                                                                         
40                                                                                                                                                
41During handling of the above exception, another exception occurred:                                                                             
42                                                                                                                                                
43Traceback (most recent call last):                                                                                                              
44  File "/p/gpfs1/mtcampbe/CEESD/Experimental/svm/svmfuse/miniforge3/envs/x.svmfuse/lib/python3.9/runpy.py", line 197, in _run_module_as_main    
45    return _run_code(code, main_globals, None,                                                                                                  
46  File "/p/gpfs1/mtcampbe/CEESD/Experimental/svm/svmfuse/miniforge3/envs/x.svmfuse/lib/python3.9/runpy.py", line 87, in _run_code               
47    exec(code, run_globals)                                                                                                                     
48  File "/p/gpfs1/mtcampbe/CEESD/Experimental/svm/svmfuse/miniforge3/envs/x.svmfuse/lib/python3.9/site-packages/mpi4py/__main__.py", line 7, in \
  <module>                                                                                                                                        
49    main()                                                                                                                                      
50  File "/p/gpfs1/mtcampbe/CEESD/Experimental/svm/svmfuse/miniforge3/envs/x.svmfuse/lib/python3.9/site-packages/mpi4py/run.py", line 198, in mai\
  n                                                                                                                                               
51    run_command_line(args)                                                                                                                      
52  File "/p/gpfs1/mtcampbe/CEESD/Experimental/svm/svmfuse/miniforge3/envs/x.svmfuse/lib/python3.9/site-packages/mpi4py/run.py", line 47, in run_\
  command_line                                                                                                                                    
53    run_path(sys.argv[0], run_name='__main__')                                                                                                  
54  File "/p/gpfs1/mtcampbe/CEESD/Experimental/svm/svmfuse/miniforge3/envs/x.svmfuse/lib/python3.9/runpy.py", line 288, in run_path               
55    pt_prg = pt_prg.with_transformed_program(self.transform_loopy_program)                                                                      
56  File "/p/gpfs1/mtcampbe/CEESD/Experimental/svm/svmfuse/pytato/pytato/target/loopy/__init__.py", line 142, in with_transformed_program         
57    return _run_module_code(code, init_globals, run_name,                                                                                       
58  File "/p/gpfs1/mtcampbe/CEESD/Experimental/svm/svmfuse/miniforge3/envs/x.svmfuse/lib/python3.9/runpy.py", line 97, in _run_module_code        
59    return self.copy(program=f(self.program))                                                                                                   
60  File "/p/gpfs1/mtcampbe/CEESD/Experimental/svm/svmfuse/meshmode/meshmode/array_context.py", line 1741, in transform_loopy_program             
61    _run_code(code, mod_globals, init_globals,                                                                                                  
62  File "/p/gpfs1/mtcampbe/CEESD/Experimental/svm/svmfuse/miniforge3/envs/x.svmfuse/lib/python3.9/runpy.py", line 87, in _run_code               
63    exec(code, run_globals) 
64  File "isolator_injection_run.py", line 1750, in <module>                                                                                      
65    t_unit = _alias_global_temporaries(t_unit)                                                                                                  
66  File "/p/gpfs1/mtcampbe/CEESD/Experimental/svm/svmfuse/meshmode/meshmode/array_context.py", line 478, in _alias_global_temporaries            
67    temp_to_iel_start = {tv: min(iels, key=lambda x: iel_order[x])                                                                              
68  File "/p/gpfs1/mtcampbe/CEESD/Experimental/svm/svmfuse/meshmode/meshmode/array_context.py", line 478, in <dictcomp>                           
69    temp_to_iel_start = {tv: min(iels, key=lambda x: iel_order[x])                                                                              
70ValueError: min() arg is an empty sequence                                                                                                      
71    main(restart_filename=restart_filename, target_filename=target_filename,                                                                    
72  File "/p/gpfs1/mtcampbe/CEESD/Experimental/svm/svmfuse/mirgecom/mirgecom/mpi.py", line 157, in wrapped_func                                   
73    func(*args, **kwargs)                                                                                                                       
74  File "isolator_injection_run.py", line 994, in main                                                                                           
75    flow_ref_state = force_evaluation(actx, flow_ref_state)                                                                                     
76  File "/p/gpfs1/mtcampbe/CEESD/Experimental/svm/svmfuse/mirgecom/mirgecom/simutil.py", line 578, in force_evaluation                           
77    return actx.thaw(actx.freeze(expn))                                                                                                         
78  File "/p/gpfs1/mtcampbe/CEESD/Experimental/svm/svmfuse/arraycontext/arraycontext/impl/pytato/__init__.py", line 419, in freeze                
79    pt_prg = pt_prg.with_transformed_program(self.transform_loopy_program)                                                                      
80  File "/p/gpfs1/mtcampbe/CEESD/Experimental/svm/svmfuse/pytato/pytato/target/loopy/__init__.py", line 142, in with_transformed_program         
81    return self.copy(program=f(self.program))                                                                                                   
82  File "/p/gpfs1/mtcampbe/CEESD/Experimental/svm/svmfuse/meshmode/meshmode/array_context.py", line 1741, in transform_loopy_program             
83    t_unit = _alias_global_temporaries(t_unit)                                                                                                  
84  File "/p/gpfs1/mtcampbe/CEESD/Experimental/svm/svmfuse/meshmode/meshmode/array_context.py", line 478, in _alias_global_temporaries            
85    temp_to_iel_start = {tv: min(iels, key=lambda x: iel_order[x])                                                                              
86  File "/p/gpfs1/mtcampbe/CEESD/Experimental/svm/svmfuse/meshmode/meshmode/array_context.py", line 478, in <dictcomp>                           
87    temp_to_iel_start = {tv: min(iels, key=lambda x: iel_order[x])                                                                              
88ValueError: min() arg is an empty sequence                                                                                                      
892022-09-12 14:38:37,855 - INFO - meshmode.array_context - Transforming kernel with 7 statements.                                                
902022-09-12 14:38:37,910 - INFO - meshmode.array_context - Transforming kernel with 55 statements.                                               
912022-09-12 14:38:37,926 - INFO - meshmode.array_context - Transforming kernel with 55 statements.                                               
922022-09-12 14:38:37,978 - INFO - meshmode.array_context - Transforming kernel with 55 statements.                                               
932022-09-12 14:38:38,004 - INFO - meshmode.array_context - Array Contraction: Contracting 7 temps                                                
94Traceback (most recent call last):                                                                                                              
95  File "/p/gpfs1/mtcampbe/CEESD/Experimental/svm/svmfuse/arraycontext/arraycontext/impl/pytato/__init__.py", line 390, in freeze
(After this just MPI Abort)
```

Here's the YAML config file:
```
nviz: 100
nrestart: 100
nhealth: 1
nstatus: 100
current_dt: 1.0e-13
t_final: 2.e-12
order:  3
dimen: 3
mach_inj: 0.8
nspecies: 7
pyro_temp_iter: 1
pyro_temp_tol: 1.e-2
alpha_sc: 0.1
s0_sc: -5.0
kappa_sc: 0.5
integrator: euler
#health_pres_min: 1
#health_pres_max: 500000
#health_mass_frac_min: -1
#health_mass_frac_max: 10
health_pres_min: 1.0e3
health_pres_max: 4.0e5
health_mass_frac_min: -1.e-3
health_mass_frac_max: 1.5
```

**Comment by MTCam** [comment]
Is this resolved for good, or should we leave it open?  @kaushikcfd , @matthiasdiener ?
